import random

R_EATING = "I don't like eating anything because I'm a bot obviously!"
R_ADVICE = "Why Sastra?"
engineering_admission="Admission to the B-Tech / 5-year Integrated M-Tech programs will be conducted under two streams.\n(1) Stream 1 (based on JEE(Main) 2021 scores and +2 Marks) for 70% of seats.\n(2) Stream 2 (based on +2 marks) for 30% of seats.\n<a href=" 'https://www.sastra.edu/admissions.html' " target='_blank' >-CLICK HERE-</a> for more info."
PG_admission= "For all PG programmes,admissions will be made on the basis of the scores in the qualifying UG / PG degree programme.\nGATE qualified candidates will be given preference for Engineering programmes.\nFor MBA, students with good CAT / XAT / AIMAT / CMAT / AIMCAT scores will be given preference.\n<a href=" 'https://www.sastra.edu/admissions.html' " target='_blank' >-CLICK HERE-</a> for more info." 
law_admission= "For all degree programmes in Law,\nadmissions will be based on the CLAT 2021 Scores and +2 aggregate. taken in the ratio of 25% : 75% respectively.\n<a href=" 'https://www.sastra.edu/admissions.html' " target='_blank' >-CLICK HERE-</a> for more info." 
other_admissions= "For degree programmes in Sciences, Arts, Commerce, Education, etc,\nadmissions will be based on the qualifying exam marks.\n<a href=" 'https://www.sastra.edu/admissions.html' " target='_blank' >-CLICK HERE-</a> for more info." 
nri_admission= "As per the Government norms, provision is made for NRI admissions.\nInterested students may kindly contact the Office of admissions as per details given on website.\n<a href=" 'https://www.sastra.edu/admissions.html' " target='_blank' >-CLICK HERE-</a> for more info." 
quota_availability= "There is reservation made under three categories - 'Thanjavur quota', 'Trichy quota' and 'Tamilnadu quota'.\n<a href=" 'https://www.sastra.edu' " target='_blank' >-CLICK HERE-</a> for more info." 
courses_offered= "B.Tech., 5-Year integrated M.Tech., M.Tech., M.Sc. (2-year programmes in Biotechnology, Chemistry, Data Sciences, Molecular Genetics, Bio-Informatics & Physics),\nM.C.A., M.B.A., B.Com. (CA), B. Com. (BFSI), B.A./B.Com./B.B.A., LL.B, (Hons.) ,\nB.Sc./B.A., B.Ed. (4-year integrated programmes in English, Mathematics & Physics),\nM.Sc. (5-year integrated programmes in Biotechnology, Chemistry, Data Sciences & Physics),\nM. Optom & B. Optom in its Main Campus in Thanjavur.\n\n\nB. Sc., B.Com, B.B.A., B.C.A., M.Sc. (Computer Science, Mathematics, Bio-Chemistry & Microbiology),\nM.Com. and B. Tech. (CSE & ECE) courses are offered in \nSrinivasa Ramanujan Centre (off-campus centre of SASTRA recognized by Govt. of India) in Kumbakonam.\n<a href=" 'https://www.sastra.edu/academics/programmes.html' " target='_blank' >-CLICK HERE-</a> for more info." 
contact_details= "CONTACT-FOR GENERAL QUERIES :\n\nSASTRA DEEMED UNIVERSITY,\nTirumalaisamudram,\nThanjavur - 613401,\nTamilnadu,\nIndia.\n\nCONTACT-FOR ADMISSION RELATED QUERIES :\n\nadmissions@sastra.edu" 
end_conversation= ["Glad to help you!", "Thanks for approaching us regarding queries!", "Wish you a fruitful journey ahead!"][random.randrange(3)]
about_sastra= "to know about SASTRA : <a href=" 'https://www.sastra.edu/about-us/sastra.html' " target='_blank' >-CLICK HERE-</a>\nAccredition & Ranking of SASTRA : <a href=" 'https://www.sastra.edu/about-us/accreditation-ranking.html' " target='_blank' >-CLICK HERE-</a>"
fee_structure= "For detailed info regarding fee structure of different courses,\n<a href=" 'https://www.sastra.edu/admissions/tuition-fees/fee-structure.html' " target='_blank' >-CLICK HERE-</a>"
hostel_availability= "Hostel facilities are available for both boys and girls separately.\n<a href=" 'https://www.sastra.edu/infrastructure/amenities/hostel.html' " target='_blank' >-CLICK HERE-</a> to know more info about hostels in SASTRA."
student_web_interface= "<a href=" 'https://webstream.sastra.edu/sastrapwi/' " target='_blank' >-CLICK HERE-</a> to access Student web interface." 
parent_web_interface= "<a href=" 'https://webstream.sastra.edu/sastraparentweb/' " target='_blank' >-CLICK HERE-</a> to access Parent web interface."
gym_facility= "gyms are available in SASTRA.\n<a href=" 'https://www.sastra.edu/infrastructure/amenities/sports.html' " target='_blank' >-CLICK HERE-</a> to check different sports facilities available." 
badminton_facility= "shuttle courts are available in SASTRA.\n<a href=" 'https://www.sastra.edu/infrastructure/amenities/sports.html' " target='_blank' target='_blank' >-CLICK HERE-</a> to check different sports facilities available."
football_facility= "Football ground is available in SASTRA.\n<a href=" 'https://www.sastra.edu/infrastructure/amenities/sports.html' " target='_blank' >-CLICK HERE-</a> to check different sports facilities available."
cricket_facility= "Cricket ground is available in SASTRA.\n<a href=" 'https://www.sastra.edu/infrastructure/amenities/sports.html' " target='_blank' >-CLICK HERE-</a> to check different sports facilities available." 
athletics_facility= "There is space available for athletics in SASTRA.\n<a href=" 'https://www.sastra.edu/infrastructure/amenities/sports.html' " target='_blank' >-CLICK HERE-</a> to check different sports facilities available."
tennis_facility= "Tennis courts are available in SASTRA.\n<a href=" 'https://www.sastra.edu/infrastructure/amenities/sports.html' " target='_blank' >-CLICK HERE-</a> to check different sports facilities available."
archery_facility= "Currently there is no provision for archery.\n<a href=" 'https://www.sastra.edu/infrastructure/amenities/sports.html' " target='_blank' >-CLICK HERE-</a> to check different sports facilities available." 
swimming_facility= "Currently there is no facility available for swimming.\n<a href=" 'https://www.sastra.edu/infrastructure/amenities/sports.html' " target='_blank' >-CLICK HERE-</a> to check different sports facilities available."
basketball_facility= "Basketball courts are available in SASTRA.\n<a href=" 'https://www.sastra.edu/infrastructure/amenities/sports.html' " target='_blank' >-CLICK HERE-</a> to check different sports facilities available." 
billiards_facility= "Facilities for playing billiards is available in SASTRA.\n<a href=" 'https://www.sastra.edu/infrastructure/amenities/sports.html' " target='_blank' >-CLICK HERE-</a> to check different sports facilities available."
table_tennis_facility= "Table tennis is available in SASTRA.\n<a href=" 'https://www.sastra.edu/infrastructure/amenities/sports.html' " target='_blank' >-CLICK HERE-</a> to check different sports facilities available." 
carrom_facility= "Carrom is available in SASTRA.\n<a href=" 'https://www.sastra.edu/infrastructure/amenities/sports.html' " target='_blank' >-CLICK HERE-</a> to check different sports facilities available."
sports_facility= "There are football ground, Cricket ground, Basketball courts, Tennis courts and\nMARUTI INDOOR STADIUM for indoor games available in SASTRA.\n<<a href=" 'https://www.sastra.edu/infrastructure/amenities/sports.html' " target='_blank' >-CLICK HERE-</a>> to check different sports facilities available." 
library_facility= "Saraswathi Sadan - central library of the university contains 1,02,600 books and covering the area of 47,000 sq.ft with modern facilities.\n<a href=" 'https://www.sastra.edu/infrastructure/library.html' " target='_blank' >-CLICK HERE-</a> to know more about the library." 
canteen_facility= "There are three canteens available inside the Campus.\n<a href=" 'https://www.sastra.edu/infrastructure/canteen-bookstore.html' " target='_blank' >-CLICK HERE-</a> to know more." 
research_facility= "SASTRA provides best lab and research facilities for academic and research purposes.\n<a href=" 'https://www.sastra.edu/research/central-facilities.html' " target='_blank' >-CLICK HERE-</a> to check the facilities available" 
wifi_facility= "SASTRA provides high speed internet connectivity to registered devices inside campus.\n<a href=" 'https://www.sastra.edu/jaze/' " target='_blank' >-CLICK HERE-</a> to know about wi-fi registration process."
events= "There are three main events in SASTRA.\n'Kuruksastra'-Cultural fest, 'Daksh'-Technical fest, 'Colosseum'-Sports fest\nKnow more about :\n'Kuruksastra' - <a href=" 'https://www.sastra.edu/student-activities/kuruksastra.html' "  target='_blank' >-CLICK HERE-</a>\n'Daksh' - <a href=" 'https://www.sastra.edu/student-activities/daksh.html' " target='_blank' >-CLICK HERE-</a>\n'Colosseum' - http://colosseum.sastra.edu/2016/"
cultural_events= "Kuruksastra, SASTRA's cultural bonanza consists of arts, music, literary events(English, Tamil and Hindi) and dance.\nTop Institutes from all over India turn up to give fierce competition to each other\nin the race to win the ultimate prize- the title of overall championship at Kuruksastra.\n<a href=" 'https://www.sastra.edu/student-activities/kuruksastra.html' " target='_blank'  >-CLICK HERE-</a> to know more."
sport_events= "SASTRA University proudly entered the tradition of holding annual Sports Fests with Colosseum in 2008.\nHosting 10 games with more than 1800 participants from different geographies of the country,\nover four days of complete gaming and sports.\nhttp://colosseum.sastra.edu/2016/ to know more." 
technical_events= "DAKSH, the international techno-management festival of SASTRA University, is an annual event comprising of a myriad of events involving all trades of engineering.\n<a href=" 'https://www.sastra.edu/student-activities/daksh.html' " target='_blank' >-CLICK HERE-</a> to know more."
foul_word="I Recognise an Offensive word"
def unknown():
    response = ["Could you please re-phrase that?. try typing -> 'Engineering Admission' 'PG Admission' 'fee structure' ",
                "Hi I am here to answer any of your question regarding SASTRA University.<br><br>Please type in your Questions.<br>",
                "What does that mean?"][
        random.randrange(3)]
    return response